apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-service-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/AndrewKMwangi/baraza-banking-gitops.git
    targetRevision: main
    path: customer-service/chart

    helm:
      valueFiles:
        - values-gitops-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: baraza-banking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
