replicaCount: 3

image:
  repository: ghcr.io/andrewkmwangi/customer-service
  tag: bccff360c445631d47f36ed19a2aba76eef2ec57
  pullPolicy: IfNotPresent

startupProbe:
  tcpSocket:
    port: 8080
  periodSeconds: 10
  failureThreshold: 15
